#%RAML 1.0 Trait
  
    headers:
      X-Rapidapi-Key: 
        example: 3023a67861msh0eb707c9fd31682p12e9c9jsn4bd95787f3d4
      X-Rapidapi-Host:
        example: walmart.p.rapidapi.com

    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
          description: Bad response from authorization server