http:
  port: "8081"

walmart:
  host: "![Ice29R5BakM2MLoKEW8OEmN1/VKwUhUvZc7cAFqVeYw=]"
  port: "![Gvj0O4ad4VG9Hjo4FepdlQ==]"
  protocol: "![hIV5C0UIkr8oIfCTCyNL+A==]"
  basepath: "/"
  RapidapiHost: "![Ice29R5BakM2MLoKEW8OEmN1/VKwUhUvZc7cAFqVeYw=]"
  RapidapiKey: "![ULyGPvoudwN5tZnlOThobpmX+McXYAkVDbhBvBI17CSh4ILJalQvmX7zb5ScqfhaAs6mHQo7pm27LeUfJzZ29g==]"
  
db:
 user: "![NcDfiv3a3x3PnwUAUkHZNA==]"
 password: "![3QCrYLPD1tiWTfkesetdaA==]"
 database: "![RjT8FSadL/t/BpkLs6dEWg==]"
 host: "![rmDpUC/qvPz8J45m0Yz4hQ==]"
 port: "![2OTI5QN1ch5FRRwIPEAX0A==]"
 